### ISSUE TITLE
Content font size

### ISSUE THREAD

**Issue by icaroperseo** [gapan/salix-startup-guide#12]
Hi!

It would be nice to have a font size a little bigger for the content of the online guide because for some people might be a little uncomfortable to read in this way. I understand that it is always possible to zoom from the web browser but think it would be much better to be offered by default.

What do you think?

Thanks in advance!

**Comment by gapan** [comment]
I think it's better after this commit: https://github.com/gapan/salix-startup-guide/commit/5407732f3a2243c2343ac26872b98fb53b320d2f
