### ISSUE TITLE
Sourcery

### ISSUE THREAD

**Issue by hugok79** [gapan/salix-startup-guide#13]
https://github.com/gapan/salix-startup-guide/blob/885c173e967c07107460e392002e8cd72f884ae6/at_a_glance.t2t#L68

Since **Sourcery** is no longer available in version **15.0** it would be better to mention e.g **"Sourcery(only in older versions)"**

Just an observation...

**Comment by gapan** [comment]
Thanks, I missed that. Fixed now.
